<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>robot_bringup</name>
  <version>0.0.0</version>
  <description>系统级 bringup 包，负责组合 teleop、hardware、simulation 等运行链路</description>
  <maintainer email="chenpeel@foxmail.com">chenpeel</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>execution_manager</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>parallel_3dof_controller</exec_depend>
  <exec_depend>sensor_hardware</exec_depend>
  <exec_depend>servo_hardware</exec_depend>
  <exec_depend>simulation_bridge</exec_depend>
  <exec_depend>speech_interface</exec_depend>
  <exec_depend>task_api_msgs</exec_depend>
  <exec_depend>task_service_bridge</exec_depend>
  <exec_depend>websocket_bridge</exec_depend>
  <exec_depend>vision_perception</exec_depend>

  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
