<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>simulation_bridge</name>
  <version>0.0.0</version>
  <description>仿真桥接包，承接 simulation 域与当前舵机链路之间的消息互转</description>
  <maintainer email="chenpeel@foxmail.com">chenpeel</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <depend>rclpy</depend>
  <depend>servo_msgs</depend>
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>sim_servo_bridge_cpp</exec_depend>

  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
