controller_manager:
  ros__parameters:
    update_rate: 50

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    imu_broadcaster:
      type: imu_sensor_broadcaster/IMUSensorBroadcaster

    position_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

imu_broadcaster:
  ros__parameters:
    sensor_name: imu_sensor
    frame_id: imu_link

position_trajectory_controller:
  ros__parameters:
    joints:
      - example_bus_joint
      - example_pca_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
